### ISSUE TITLE
[REQUEST] Visual or audio cue for number of times a shopping list is completed

### ISSUE THREAD

**Issue by rbpaiett** [nikkisaurus/FarmingBar#1]
**Describe the feature you'd like**
What I'd like is a toggle between displaying the current count of items and the current number of completed objectives on the buttons themselves.  I do realize that the number of completed objectives is already a feature on the tooltips.  That way sometimes I want to see total items and other times I want to see total number of times a shopping list is completed.  That way if I have a shopping list for a particular armor or weapon, I can see 'how many' of those weapons or armor I can currently make.  This really helps with farming for profession levelling.

**Describe alternatives you've considered**
Perhaps simply have an audio cue for when an objective is completed a 2nd, 3rd, 4th, 5th, etc. time.  Either one is great for me.

**Comment by niketa-wow** [comment]
Hello.

In the upcoming 3.0 alpha, I've started implementing a new objective structure. As such, the way you create shopping lists has changed. You essentially will create an objective, add the items as trackers and set individual tracker objectives. You then select All as a tracker condition.

The overall count of an objective will only increase once all trackers are complete. Basically the new objectives by default will show the number of times completed in a shopping list.

My question is now: what are the scenarios where you like to see the cumulative count the way the shopping lists are currently implemented?

I have tooltips showing count toward the objective and total count but no total between all items. Is this something you'd like to keep? And what's an example where this helps?

Thanks!

**Comment by nikkisaurus** [comment]
Could you provide some insight on this request now that the rewrite is almost complete? Is this something that you're still hoping to have implemented or have the changes in the rewrite made this redundant?

**Comment by rbpaiett** [comment]
Actually it works fine now. Looks like one of your fixes put it right.
