### ISSUE TITLE
[REQUEST] Alert Chat window output selection

### ISSUE THREAD

**Issue by MrsAngelD** [nikkisaurus/farmingbar#22]
Would it be possible to select which chat window to output alerts to?? For example, I use elvui, and they have a separate window which is used specifically for loot, I would like to be able to output farming bars alerts to that window.

Thank you so much!

**Comment by niketa-wow** [comment]
This is something I can definitely implement. If it's more involved it may have to wait for version 3, but if it's simple I can add it to the stable.

I'll have to look into it next week as I'm not home.

**Comment by MrsAngelD** [comment]
@niketa-wow Thank you so much :) and I am happy to be patient...I appreciate all the work you've put into this addon it's fantastic!

**Comment by shepker** [comment]
I would like to second this request.  This would be a very useful feature.

**Comment by niketa-wow** [comment]
I've implemented a basic version of this in release v2.1.5. At the moment, you can select the chat frame for alerts only. I plan on expanding upon it in the alpha version later on. It will implement a setting for general addon messages and per bar settings.
