### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by rbpaiett** [nikkisaurus/farmingbar#41]
**Describe the bug**
This error appeared upon logging on after the update:

1x FarmingBar\Modules\Bars.lua:101: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@FarmingBar\Modules\Bars.lua"]:101: in function `ReleaseAllBars'
[string "@FarmingBar\Modules\Bars.lua"]:87: in function `InitializeBars'
[string "@FarmingBar\FarmingBar-v3.0.0.lua"]:15: in function <FarmingBar\FarmingBar.lua:14>
[string "=[C]"]: ?
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@ArkInventory\Core\ArkInventory-31000.8.lua"]:10739: in function `LoadAddOn'
[string "@ArkInventory\Core\ArkInventory-31000.8.lua"]:10768: in function `BlizzardAPIHook'
[string "@ArkInventory\Core\ArkInventory-31000.8.lua"]:2837: in function <ArkInventory\Core\ArkInventory.lua:2806>
[string "=[C]"]: ?
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Client**
WotLK Classic

**To Reproduce**
1. Update to latest
2. Log in.

**Expected behavior**
Expected the addon to load, got no farming bars.

**Screenshots**
No screenshots needed or provided.

**Additional context**
No additional contexts needed.

**Comment by rbpaiett** [comment]
UPDATE:  Ok, it seems that curseforge didn't load it properly and I did it again and now it works.  However my previous bars have disappeared from the HUD and the old ones got sort of archived into templates.  Not sure if that's what it's supposed to do.

**Comment by nikkisaurus** [comment]
Yes, that is the intended behavior due to the way the database and profiles have been changed. By default now profiles are shared between toons and you create new profiles for different setups.
