### ISSUE TITLE
[FEATURE REQUEST] Ok, here's what changes I would make.  I see in the tooltip you have:

### ISSUE THREAD

**Issue by nikkisaurus** [nikkisaurus/FarmingBar#43]
Ok, here's what changes I would make.  I see in the tooltip you have:

a (b/c) [d]

I'd like a = total tracker goals completed, b = total items in my inventory, c = tracker goal.  For me, d isn't necessary.  What you have above for 'count' and 'goal' takes care of the overall goal that's listed in the top left of the button.  So putting it a (b/c) per tracker as I have it listed in my preferences would be perfect.

_Originally posted by @rbpaiett in https://github.com/nikkisaurus/FarmingBar/issues/42#issuecomment-1290137114_

**Comment by nikkisaurus** [comment]
[d] represents the total number necessary to complete the overall goal. For example, if you have a tracker with a goal of 2, and an objective of 10, [d] would be 20, because you need 20 of the tracker to complete the overall goal. So if you have 10, the tooltip would look like:

5 (10/2) [20]

So I gather I have 5 of the tracker completed, and I need 20 to meet my overall objective of 10.

**Comment by rbpaiett** [comment]
Oh I see. Well, however you have it set up, I just want somewhere where I can see the total number of items right now in my inventory and where it fits in the gathering scheme.

**Comment by nikkisaurus** [comment]
Gotcha, so the way it is, what you want is there in the a (b/c) aspect. [d] is basically just extra information. b is your total inventory.

**Comment by rbpaiett** [comment]
yes exactly.

**Comment by rbpaiett** [comment]
Fantastic, the latest update has made the tooltip totals appear EXACTLY the way I wanted it all along, THANK YOU!!!
