### ISSUE TITLE
[Bug]: Bank include doesn't work "well"

### ISSUE THREAD

**Issue by modnarwave** [nikkisaurus/FarmingBar#44]
### Interface Version

10.0

### AddOn Version

v3

### Have you replicated this error without any other addons loaded?

Yes

### What steps did you take leading up to this issue?

When setting "include bank" to true, and moving items to bank, the correct number of item is showed on the bar, but if i get another one of the item in my bag, only the number of items in my bags are shown

**Comment by nikkisaurus** [comment]
Are you using DataStore?
What item are you having this issue with?
How are you getting another of the item?

For example, if I test using mage cake, I include bank, and move the cake to the bank. Then I create more cake and my count updates. I'm guessing you're not getting a bag update event if this doesn't work for you.

**Comment by modnarwave** [comment]
Yes i am using datastore, I'm having the issue with arcane cristals
I'm farming the item by mining

**Comment by modnarwave** [comment]
just retried without datastore, it's now working fine so i guess the problem is from datastore :) thank you for the help and sorry for the inconvenience :)
