### ISSUE TITLE
[Bug]: Latest update conflicts with latest Altoholic, particularly Datastore.

### ISSUE THREAD

**Issue by rbpaiett** [nikkisaurus/FarmingBar#46]
### Interface Version

3.4.0

### AddOn Version

3.7.3-wrath

### Have you replicated this error without any other addons loaded?

Yes

### What steps did you take leading up to this issue?

I enabled only this addon plus Altoholic (ver 3.4.001 Wotlk Classic) and Datastore which comes with it.

9x Interface\AddOns\FarmingBar\Modules\DataStore-2022.10.25.lua:34: attempt to perform arithmetic on local 'reagentBag' (a nil value)
[string "@Interface\AddOns\FarmingBar\Modules\DataStore-2022.10.25.lua"]:34: in function `GetDataStoreItemCount'
[string "@Interface\AddOns\FarmingBar\Modules\Counts.lua"]:62: in function `GetTrackerCount'
[string "@Interface\AddOns\FarmingBar\Modules\Counts.lua"]:19: in function `GetObjectiveWidgetCount'
[string "@Interface\AddOns\FarmingBar\Widgets\Button.lua"]:409: in function `SetCount'
[string "@Interface\AddOns\FarmingBar\Widgets\Button.lua"]:629: in function `UpdateAttributes'
[string "@Interface\AddOns\FarmingBar\Widgets\Button.lua"]:622: in function `Update'
[string "@Interface\AddOns\FarmingBar\Widgets\Button.lua"]:496: in function `SetID'
[string "@Interface\AddOns\FarmingBar\Widgets\Bar.lua"]:111: in function `DrawButtons'
[string "@Interface\AddOns\FarmingBar\Widgets\Bar.lua"]:283: in function `SetID'
[string "@Interface\AddOns\FarmingBar\Modules\Bars.lua"]:92: in function `InitializeBars'
[string "@Interface\AddOns\FarmingBar\FarmingBar-v3.7.3.lua"]:20: in function <Interface\AddOns\FarmingBar\FarmingBar.lua:14>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\ArkInventory\Core\ArkInventory-31007.lua"]:11232: in function `LoadAddOn'
[string "@Interface\AddOns\ArkInventory\Core\ArkInventory-31007.lua"]:11261: in function `BlizzardAPIHook'
[string "@Interface\AddOns\ArkInventory\Core\ArkInventory-31007.lua"]:3000: in function <Interface\AddOns\ArkInventory\Core\ArkInventory.lua:2969>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

### Please supply a copy of your saved variables.

All saved variables or just the relevant ones?

**Comment by nikkisaurus** [comment]
Does this issue persist in v3.7.4?

**Comment by rbpaiett** [comment]
Let me check the next time I'm on.

**Comment by rbpaiett** [comment]
Nope, looks like it's fine now, thanks.
