### ISSUE TITLE
[Bug]: On right click, the item on the bar gets used on the pressdown and pressup as well so I get an error speech.

### ISSUE THREAD

**Issue by rbpaiett** [nikkisaurus/FarmingBar#47]
### Interface Version

3.4.0

### AddOn Version

v3.7.5-wrath

### Have you replicated this error without any other addons loaded?

Yes

### What steps did you take leading up to this issue?

Just use and item on a bar and right click (error speech says 'still recharging').

**Comment by rbpaiett** [comment]
Odd, I thought this version was supposed to do the opposite.

**Comment by nikkisaurus** [comment]
That's weird cause I just added a fix in the latest version for it and I did it in classic so idk. I have something I can try next time I have a chance to update.

**Comment by nikkisaurus** [comment]
Are you still experiencing this issue?

**Comment by rbpaiett** [comment]
Unfortunately yes, I'm still experiencing this.

**Comment by nikkisaurus** [comment]
What item is causing this?

**Comment by rbpaiett** [comment]
Ok, here's the strange part.  When I use it on food, my char uses it but I get the audio error "I cannot use that" and the error "Item is not ready".  However, when I put a poison on, I get the audio error "I cannot use that" and the error "That Item is not a valid target".

**Comment by rbpaiett** [comment]
This all used to work before WotLK.

**Comment by nikkisaurus** [comment]
I think the problem is due to a change that had to be made for Dragonflight. I've added a check for classic to only register AnyDown instead of both and will push the update shortly.

**Comment by rbpaiett** [comment]
Thank you!

**Comment by rbpaiett** [comment]
Works perfect now!
