### ISSUE TITLE
[REQUEST]: Hidden Feature

### ISSUE THREAD

**Issue by DaNod123** [nikkisaurus/FarmingBar#48]
### Describe what you want to be implemented?

Hello!

I try to make a function that hide the bar when I am not in Dragon Isles but it doesn't working.
Could you please help me?

Regards!

### Explain why you want this feature implemented.

I want to change bars when I move to another map!
Thank you!

**Comment by nikkisaurus** [comment]
Under events you should add:
`ZONE_CHANGED_NEW_AREA`

For the function, you need to get the zone IDs for the dragon isles zones you want it to show up in.
`function()
    -- To hide this bar, return true
    -- To show this bar, return nil
    return C_Map.GetBestMapForUnit("player") ~= 2024
end`

The above example would hide it if not in Azure Span. For each zone, just add 
` and C_Map.GetBestMapForUnit("player") ~= ZONEID`
after the return.
