### ISSUE TITLE
[Bug]: Addon not reporting status change or alert until I swap weapons

### ISSUE THREAD

**Issue by rbpaiett** [nikkisaurus/FarmingBar#52]
### Interface Version

3.4.1

### AddOn Version

3.7.8-wrath

### Have you replicated this error without any other addons loaded?

Yes

### What steps did you take leading up to this issue?

I just used one of my FBar setups, then gathered one of the items into my inventory.  The first time it worked, after that, the only time an alert would show up was after I either used like an arrow or swapped a weapon or fishing pole.

### Please supply a copy of your saved variables.

I tried to put a copy of the saved variables but the interface said that it doesn't accept that file type :(

**Comment by nikkisaurus** [comment]
Were there any lua errors? Also I think you can change the saved variables to a text file to upload.

**Comment by rbpaiett** [comment]
No lua errors appear. It's been a few days since I logged on so lemme see how it is now.  Then I'll convert to txt so I can upload.

**Comment by rbpaiett** [comment]
Hmm, strange.  It seems to be working normally now.  I wonder if a certain update from one of the other addons had an effect.  Perhaps something hidden in the background that isn't there anymore.  I'll monitor it the rest of the day and if the problem doesn't appear again, I'll close this out.

**Comment by rbpaiett** [comment]
Ok, seems to be fine now so I'll close it out now.
