### ISSUE TITLE
[REQUEST]: Keybind for Objective Templates

### ISSUE THREAD

**Issue by rbpaiett** [nikkisaurus/FarmingBar#53]
### Describe what you want to be implemented?

For a button that has 'no' objective, how about having the keybind Ctrl-Right-Click open up the Objective Templates to use one of them.

### Explain why you want this feature implemented.

It would be easier and quicker than typing /fbar, and then click on Objective Templates.

### Describe any alternatives you've considered.

Perhaps because the keybind Ctrl-Right-Click is already in place for an 'existing' objective on a button, it might not be possible to do this request that you could set up an alternate keybind.  However Ctrl-Right-Click to access the objective templates for an empty button and edit an existing objective on a button would be easiest.

I hope my description isn't misleading or confusing.

**Comment by nikkisaurus** [comment]
This is something I've had on my todo list and just kinda forgot about as I got busy with life. I've implemented the change in [v3.8.0](https://github.com/nikkisaurus/FarmingBar/releases/tag/v3.8.0). It will allow you to apply an existing template to an empty button through the objective editor.

I haven't decided if I should allow creating a new template from an empty button. If anything, it would be a button that just creates a button only template similar to a normal template, but then you could use the save as template button that is already on the editor. Just not sure if it's worth doing this or not.

**Comment by rbpaiett** [comment]
Thank you, much appreciated!
