### ISSUE TITLE
[Bug]: Not seeing bank items added to bag items

### ISSUE THREAD

**Issue by mgouges2** [nikkisaurus/FarmingBar#62]
### Interface Version

1.14.4

### AddOn Version

1.14.4

### Have you replicated this error without any other addons loaded?

Yes

### What steps did you take leading up to this issue?

Nothing

### Did you encounter any Lua errors related to this issue? If so, please provide them here.

No

### Please supply a copy of your saved variables. You may need to save the file as a .txt file to upload here.

[FarmingBar.txt](https://github.com/nikkisaurus/FarmingBar/files/12566597/FarmingBar.txt)

**Comment by nikkisaurus** [comment]
I don't know why I didn't see this ticket when I was addressing your other one, but this issue looks to be the same as another previous one, which the user hasn't responded to the last request for information.

Would you mind checking it out and seeing if you can answer any questions that may point me toward replicating and fixing the issue?

https://github.com/nikkisaurus/FarmingBar/issues/57#issuecomment-1707755611

Thanks!

**Comment by mgouges2** [comment]
Will do.  Not sure if it’s still an issue but I will check it out and get back.

Mark Gouge
Sent from iPhone

________________________________

**Comment by mgouges2** [comment]
Quick question, should the count on the bar always include items in both bags and bank on each character?


________________________________

**Comment by nikkisaurus** [comment]
Only if you have include bank selected. By default it should not include them.

**Comment by mgouges2** [comment]
Ahh I just figured out how to set up objective tracker and include/exclude the bank.  My mistake.  You can close this ticket.  Thanks again for all your help.  I can only hope you will continue to make addons for WoW.  If you have any questions feel free to reach out. Lexock
________________________________

**Comment by nikkisaurus** [comment]
Glad it's working for you. If you have any other issues, feel free to open another ticket.
