### ISSUE TITLE
Auction House selling does not update bar

### ISSUE THREAD

**Issue by mgouges2** [nikkisaurus/FarmingBar#63]
### Interface Version

1.14.4

### AddOn Version

1.14.4

### Have you replicated this error without any other addons loaded?

Yes

### What steps did you take leading up to this issue?

When selling items through the Auction house, amounts on Farming bar do not update.

### Did you encounter any Lua errors related to this issue? If so, please provide them here.

no

**Comment by nikkisaurus** [comment]
Are you using altoholic for account wide counts or just the basic counts?

I think I may be able to add an update to the bars in response to an event, but I'll need to look into which event it is.

Also, I don't currently have an active sub, so I will not be able to test it in classic and I'm not sure if I can actually post auctions without a sub in retail.

I will try to do what I can, but if I need to resub, it may take me just a little longer to fix.

**Comment by mgouges2** [comment]
Hello, thank you for responding to my issue.

I do use Altoholic  on Classic SoD.

On Retail, Farming Bar works correctly, updating the amount on the bar when selling through the auction.

On Classic SoD, it does not update the count on Farming Bar when selling to the Auction.  I do use Auctionator on both accounts.

If I can help in any other way let me know.  I can gift game time for 6o days.  I don't mind doing this if it helps the development community provide addons to the gaming community.  I would just need your Real ID or Battletag to send the gift.

Thanks,
Lexock
________________________________

**Comment by nikkisaurus** [comment]
Ok just to be clear,you use altoholic on classic, but not on retail?

Also that would be wonderful if you could gift the time. I have a fix I need to look into for another addon as well, but I'm having some car troubles and can't really afford a sub myself at this moment.

If you do, thank you. If not, no worries. I'll do the best I can with the free access on retail. :) 

My battle tag is Niketa#1952.

**Comment by mgouges2** [comment]
Yes I only use altoholic on classic SoD.

I sent a friend request, once it comes through, I will gift you sub time.

Thanks,
Lexock
________________________________

**Comment by nikkisaurus** [comment]
It went through and I accepted it.

**Comment by mgouges2** [comment]
Ok just tried to send gift but it requires a friend to be a friend for 3 days.  I will try again in 3 days.  Sorry

Mark Gouge
Sent from iPhone

________________________________

**Comment by nikkisaurus** [comment]
No problem!

**Comment by mgouges2** [comment]
Hello,

I just sent the game time for 60 days.  According to Blizzard they should be sending you info on how to collect.  Thanks again and if you need anything else from me, please let me know.

Lexock

Mark Gouge
Sent from iPhone

________________________________

**Comment by nikkisaurus** [comment]
Thank you! I should be able to login and test some things by the weekend, and if I have time during the week as well, I will. It's always unpredictable how much time I have on week days.

**Comment by nikkisaurus** [comment]
Ok, just wanted a little more clarification. Do you mean when you initially post an item on the AH, it doesn't update the count? Or do you mean the count stays included when you post something, but when it sells, it doesn't update?

**Comment by mgouges2** [comment]
Yes, Do you mean when you initially post an item on the AH, it doesn't update the count.  This is correct.  Example: I have 10 sliver leaf in my bags and showing on the bar.  I sell them through the AH with Auctionator.  They are removed from my bags.  The icon for Silver leaf is still on the Farmingbar ( i expect this) but the count remains at 10.  If i did the same transaction but through a vendor the count would be reduced to 0 on the bar. I hope this helps.  Thanks for working on this issue.

Mark Gouge
Sent from iPhone

________________________________

**Comment by nikkisaurus** [comment]
Gotcha. So, with Altoholic, it includes the count for items you have on the AH, since technically you still *have* the item until it is either sold or cancelled. I can implement an option to ignore posted auctions in the count, though, if you don't like this behavior.

**Comment by mgouges2** [comment]
Yes, if you could implement an option to  ignore posted auctions in the count that would be great.  Thank you for your help in finding a solution.

Mark Gouge
Sent from iPhone

________________________________

**Comment by nikkisaurus** [comment]
I'm so sorry, it was a busy week for me. I will see if I can do it tonight after work. It should be a pretty quick option to add. If not tonight, in the next couple days.

**Comment by mgouges2** [comment]
No worries.  Thanks for your help.

Mark Gouge
Sent from iPhone

________________________________

**Comment by nikkisaurus** [comment]
Implemented in [v3.10.1](https://github.com/nikkisaurus/FarmingBar/releases/tag/v.3.10.1). If there are any more issues related to this request, feel free to reopen this ticket. Thank you for your patience!

**Comment by mgouges2** [comment]
Looks like it works!  Thank you very much!

Mark Gouge
Sent from iPhone

________________________________
