### ISSUE TITLE
[Bug]: No longer able to Bank items added to bag items (was fixed in 1.14.4)

### ISSUE THREAD

**Issue by mgouges2** [nikkisaurus/FarmingBar#66]
### Interface Version

3.11.0

### AddOn Version

11.02

### Have you replicated this error without any other addons loaded?

Yes

### What steps did you take leading up to this issue?

See previous bug report #62

### Did you encounter any Lua errors related to this issue? If so, please provide them here.

no

**Comment by nikkisaurus** [comment]
Should be fixed in [v3.11.1](https://github.com/nikkisaurus/FarmingBar/releases/tag/v3.11.1), but please reopen if it still continues to be an issue.

**Comment by mgouges2** [comment]
Hello,

I don't see the bank include setting in 3.11.1  Is it under Settings?

Thanks,
Mark
________________________________

**Comment by nikkisaurus** [comment]
You adjust it via the objective editor either directly on the bar or you can edit the template under settings and then drag it on the bar. 

To do it with one already on the bar, default is control right click to open the editor, then go to trackers, then include bank.

**Comment by mgouges2** [comment]
Got it.  It works great.  Thank you.

Mark Gouge
Sent from iPhone

________________________________
