### ISSUE TITLE
[Bug]: Bar is not showing after the Sept 24th WoW update

### ISSUE THREAD

**Issue by roweboy1974** [nikkisaurus/FarmingBar#68]
### Interface Version

1.15.4

### AddOn Version

3.11.1

### Have you replicated this error without any other addons loaded?

Yes

### What steps did you take leading up to this issue?

I installed this today because FarmIt does not work. But neither does this. All I see is the anchor but no bars.

### Did you encounter any Lua errors related to this issue? If so, please provide them here.

No

### Please supply any screenshots relevant to this issue.

![Screenshot 2024-09-26 110558](https://github.com/user-attachments/assets/489f8336-0f57-4e4f-a022-ec30e2a039b9)

### Please supply a copy of your saved variables. You may need to save the file as a .txt file to upload here.

[FarmingBar.txt](https://github.com/user-attachments/files/17151012/FarmingBar.txt)

**Comment by nikkisaurus** [comment]
Can you bring up the config either by typing /farmingbar or right clicking the anchor?

If so, check under the settings to see how many buttons are enabled.

**Comment by roweboy1974** [comment]
nvm... I found my problem... thanks!
